models.py
#!/usr/bin/env python
__author__ = 'XeanYu'
from exts import db
from flask_login import UserMixin
from exts import login_manager
from func.date import now
# Log Users
class Users(db.Model,UserMixin):
    __tablename__ = 'users'

    uid = db.Column(db.Integer,primary_key=True)

    username = db.Column(db.String(64),unique=True,nullable=False,index=True)

    password = db.Column(db.String(124),nullable=False,index=True)

    mail = db.Column(db.String(124),index=True,nullable=False)

    code = db.Column(db.String(40),nullable=False)

    sgin_up_date = db.Column(db.String(64))

    vip = db.Column(db.String(64),default=0) # judgment have vip
    attract = db.Column(db.Integer,default=0) #


    # 表中没有id字段，自己定义返回uid字段
    def get_id(self):
        return self.uid

@login_manager.user_loader
def user_load(id):
    return Users.query.get(id)

# Login log
class Login_logs(db.Model):
    __tablename__ = 'login_logs'

    id = db.Column(db.Integer,primary_key=True) # id => 主键

    username = db.Column(db.String(64),index=True) # 用户的用户名

    browser = db.Column(db.String(124),index=True) # 用户使用的浏览器

    device = db.Column(db.String(124),index=True)  # 用户使用的设备

    os = db.Column(db.String(124),index=True)  # 用户的操作系统

    ip = db.Column(db.String(64),index=True) # 用户IP地址

    platform = db.Column(db.String(12),index=True) # user's platform

    login_date = db.Column(db.String(64),default=now())

conf/__init__.py
#!/usr/bin/env python
__author__ = 'XeanYu'

func/__init__.py
__author__ = 'XeanYu'

main/__init__.py
#!/usr/bin/env python
__author__ = 'XeanYu'

# 创建蓝本
from flask import Blueprint
main = Blueprint('main',__name__)

# 在末尾导入views,errors，因为errors和views也需要导入main，避免了循环导入依赖

from . import views,errors

# .(点) 就是当前包

main/views.py
__author__ = 'XeanYu'

"""
this modle is main.views

"""

from flask import render_template,session,url_for,request,jsonify,redirect
from flask_login import login_required,login_user,logout_user
from . import main
from random import randint # make random_code
from exts import db
from models import Users,Login_logs
from func.password import * # use bcrypt make password
from func.date import now
from func.agent import *


# index view route
@main.route('/')
def index():
    return 'index'

# sgin_up view route
@main.route('/registered/',methods=['GET','POST']) # allow GET and POST request
def sgin_up():
    """
    此路由用来注册用户
    :return:
    """
    if request.method == 'GET': # GET
        global up_random_code
        up_random_code = randint(10000, 99999)  # 生成5位纯数字验证码
        return render_template('sgin_up.html',num_code=up_random_code)

    else: # POST
        username = request.form.get('username').strip() # 获取用户名
        email = request.form.get('email').strip() # 获取邮箱
        password = request.form.get('password').strip() # 获取密码
        code = request.form.get('code').strip() # 获取私密代码
        random_code_form = request.form.get('random_code').strip() # 获取随机码

        if all([username,email,password,code,random_code_form]):

            # 判断验证码是否正确
            if str(random_code_form) == str(up_random_code):

                add_db = Users.query.filter_by(username=username).first()
                if not add_db: # 判断数据是否存在当前用户，如果不存在，则添加到数据库

                    password = passwd_bcrypt(password)
                    add_db = Users(username=username,mail=email,password=password,code=code,sgin_up_date = now())
                    db.session.add(add_db)
                    db.session.commit() # 提交值数据库(Fluash())
                    return jsonify(msg='redirect')

                else:
                    return jsonify(msg='用户已存在')

            else:
                return jsonify(msg='输入的随机码不正确')

        else:
            return jsonify(msg='输入的信息不完整')

# sgin_in  view route
@main.route('/login/',methods=['GET','POST'])
def sgin_in():
    """
    此路由用来用户登录
    :return:
    """
    # if user not login ==> GO TO login
    if request.method == 'GET':
        global lg_random_code
        lg_random_code = randint(10000,99999)
        return render_template('sgin_in.html',num_code=lg_random_code) # return template and export make_random_code

    if request.method == 'POST':

        """
        strip() => cut space
        """
        username = request.form.get('username').strip() # get user's username
        password = request.form.get('password').strip() # get user's password
        random_code_form = request.form.get('random_code').strip() # get user's input random code

        # get user's msg
        user_ip = str(request.remote_addr) # get user's IP
        user_agent = str(request.user_agent) # get user's User-Agent
        browser = str(request.user_agent.browser) # get user's browser
        os = str(request.user_agent.platform)  # get user's os

        if all([username,password,random_code_form]): # judgmeng user's input not is None
            if str(lg_random_code) == str(random_code_form): # judgment random_code == user input random_code

                # search user for Users'Table
                login = Users.query.filter_by(username=username).first()
                if login: # find user

                    if check_passwd(password,login.password.encode()): # judgment password equal

                        # add user login log
                        logadd = Login_logs(
                            username=username,
                            browser=browser,
                            device=is_device(user_agent),
                            os=os,
                            ip=user_ip,
                            platform=user_msg(user_agent)
                        ) #


                        db.session.add(logadd) # add 'logadd' object to 'db.session'
                        db.session.commit() # commit session to DB's Login_logs
                        login_user(login)
                        return jsonify(msg='login') # return views to Ajax ==> Login success

                    else: # password error
                        return jsonify(msg='密码错误!')

                else:   # don's search username
                    return jsonify(msg='没有此用户,请注册')

            else:   # random error
                return jsonify(msg='随机码输入错误')

        else:  # fill message have None
            return jsonify(msg='请输入完整信息')

    # if user login

# password lost page  view route
@main.route('/getpass/',methods=['GET','POST'])
def getpass():

    """
    change password page
    :return:
    """
    if request.method == 'GET':
        return render_template('getpass.html')

    else:
        username = request.form.get('user').strip()
        code = request.form.get('user').strip()
        newpass = request.form.get('newpass').strip()

            # use all() function => True
        if all([username,code,newpass]):

            # find username for DB
            user = Users.query.filter_by(username=username).first()
            if user:
                if str(code) == str(user.code):
                    user.password = str(passwd_bcrypt(newpass))
                    db.session.add(user)
                    db.session.commit()
                    return jsonify(msg='change')

                else:
                    return jsonify(msg='私密代码不正确!')

            else:
                return jsonify(msg='没有此用户')

        else:
            return jsonify(msg='请填写好信息')

@main.route('/user/',methods=['GET','POST'])
@login_required
def console():
    return render_template('user.html')

@main.route('/logout/')
@login_required
def logout():
    logout_user()
    return redirect(url_for('main.sgin_in'))

templates/getpass.html
<!DOCTYPE html>
<!--author: XeanYu -->
<!-- 密码找回页面 -->
<html>

<head>
  <meta charset="utf-8">
    <meta name="viewport" content="width=device-width,initial-scale=1.0, minimum-scale=1.0, maximum-scale=1.0, user-scalable=no"/>
  <title>密码找回</title>

  <link rel="stylesheet" href="{{ url_for('static',filename='css/bootstrap.min.css') }}">
  <link rel="stylesheet" href="{{ url_for('static',filename='style/getpass.css') }}">
  <script type="text/javascript" src="{{ url_for('static',filename='js/jquery.min.js') }}"></script>

</head>

<body>
  <div class="container">
      <div class="row">
          <div class="col-lg-8 col-lg-push-2">
    <div class="getpass">


    <!--输入栏盒子-->
        <div class="box">

        <div class='box_title'>
            <h3 class="text-center page-header">密码找回</h3>
        </div>
            <!--input user's username-->
            <div class="user">
            <form method="post" id="form" action="{{ url_for('main.getpass') }}">

            <p class="input-title">用户名</p>
            <div class="input-group input">
                <span class="input-group-addon"><span class="glyphicon glyphicon glyphicon-search"></span></span>
                <input type="text" name="user" id="username_input" class="form-control" placeholder="请输入您的用户名" required="required"/>
            </div>

            <p class="input-title">私密代码</p>
            <div class="input-group input find">
                <span class="input-group-addon"><span class="glyphicon glyphicon-console"></span></span>
                <input type="text" name="code" id="username_input" class="form-control" placeholder="请输入您私密代码" required="required"/>
            </div>

            <p class="input-title">新密码</p>
            <div class="input-group input find">
                <span class="input-group-addon"><span class="glyphicon glyphicon-lock"></span></span>
                <input type="text" name="newpass" id="username_input" class="form-control" placeholder="新密码" required="required"/>
            </div>

                <div class="alert alert-danger" id="alert-box">
                    <span class="info glyphicon glyphicon-info-sign" id="info"></span>
                    <span class="off glyphicon glyphicon-remove-circle" id="off" onclick="off()"></span>
                </div>

            <div class="input-group input find submit">
                <button class="btn btn-danger">立即修改</button>
            </div>

            </form>
            </div>
        </div>
    </div>
    </div>
    </div>
  </div>
<script type="text/javascript" src="{{ url_for('static',filename='exts_js/getpass.js') }}"></script>
<script type="text/javascript" src="{{ url_for('static',filename='js/canvas-nest.js') }}"></script>
</body>
</html>

templates/sgin_in.html
<!DOCTYPE html>
<html lang="en">
<head>
    <!--登录页面 sgin_in-->
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width,initial-scale=1.0, minimum-scale=1.0, maximum-scale=1.0, user-scalable=no"/>
    <title>登录</title>
    <link rel="stylesheet" href="{{ url_for('static',filename='css/bootstrap.min.css') }}" />
    <link rel="stylesheet" href="{{ url_for('static',filename='style/sgin.css') }}" />
    <script type="text/javascript" src="{{ url_for('static',filename='js/jquery.min.js') }}"></script>
</head>
<body>
    <div class="container">
            <div class="row">
                <div class="col-lg-6 col-lg-push-3">
            <div class="sgin login_temp">
            <h3 class="page-header text-center size">
                <t><a href="{{ url_for('main.sgin_in') }}" class="action a">登录&nbsp;</a></t>
                <b>·</b>
                <t><a href="{{ url_for('main.sgin_up') }}" class="a login">&nbsp;注册</a></t>
            </h3>

            <div>
                <form class="form" action="{{ url_for('main.sgin_in') }}" method="post" accept-charset="UTF-8" id="user_info">

                    <div class="input">
                        <span class="glyphicon glyphicon-user"></span>
                        <input type="text" class="input_user" placeholder="用户名" name="username" required="required"/>
                    </div>

                    <div class="input">
                        <span class="glyphicon glyphicon-lock"></span>
                        <input type="password" class="input_user" placeholder="密码" name="password" required="required"/>
                        <div class="text-danger sgin_pass"><strong></strong></div>
                    </div>

                     <div>
                        <p class="text-danger" id="alert"></p>

                        <co class="code">随机码 ==> <bg class="text-danger">{{ num_code }}</bg></co>
                        <div class="input code_box">
                            <input type="text" class="input_user" placeholder="随机码" name="random_code" required="required"/>
                        </div>
                     </div>
                        <button class="sgin_btn btn btn-danger btn-block">登 录</button>
                    <p class="text-danger p"><strong><a href="{{ url_for('main.getpass') }}">忘记密码?</a></strong></p>

                </form>

            </div>
        </div></div>
    </div>
    <script type="text/javascript" src="{{ url_for('static',filename='exts_js/sgin_in.js') }}"></script>
    <script type="text/javascript" src="{{ url_for('static',filename='js/canvas-nest.js') }}"></script>
</body>
</html>

templates/sgin_up.html
<!DOCTYPE html>
<html lang="en">
<head>
    <!--注册页面 sgin_up-->
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width,initial-scale=1.0, minimum-scale=1.0, maximum-scale=1.0, user-scalable=no"/>
    <title>注册</title>
    <link rel="stylesheet" href="{{ url_for('static',filename='css/bootstrap.min.css') }}" />
    <link rel="stylesheet" href="{{ url_for('static',filename='style/sgin.css') }}" />

    <script type="text/javascript" src="{{ url_for('static',filename='js/jquery.min.js') }}"></script>

</head>
<body>

    <div class="container">
        <div class="row">
            <div class="col-lg-6 col-lg-push-3">
                <div class="sgin">
            <h3 class="page-header text-center size">
                <t><a href="{{ url_for('main.sgin_in') }}" class="a login">登录&nbsp;</a></t>
                <b>·</b>
                <t><a href="{{ url_for('main.sgin_up') }}" class="action a">&nbsp;注册</a></t>
            </h3>

            <div>
                <form class="form" action="{{ url_for('main.sgin_up') }}" method="post" accept-charset="UTF-8" id="user_info">

                    <div class="input">
                        <span class="glyphicon glyphicon-user"></span>
                        <input type="text" id="username" class=" input_user" placeholder=" 用户名" name="username" required="required"/>
                        <div class="text-warning alert_user"><strong><small>用户名长度不能超过64字节</small></strong></div>
                    </div>

                    <div class="input">
                        <span class="glyphicon glyphicon-envelope"></span>
                        <input type="email" id="email" class="input_user" placeholder=" 邮箱" name="email" required="required"/>
                        <div class="text-warning alert_email"><strong><small>邮箱长度不可以超过124字节</small></strong></div>
                    </div>

                    <div class="input">
                        <span class="glyphicon glyphicon-lock"></span>
                        <input type="password" id="password" class="input_user" placeholder=" 密码" name="password" required="required"/>
                        <div class="text-warning alert_pass"><strong><small>密码长度不可以超过124字节</small></strong></div>
                    </div>

                    <div class="input">
                        <span class="glyphicon glyphicon-console"></span>
                        <input type="text" id="code" class="input_user" placeholder=" 私密代码" name="code" required="required"/>
                        <div class="text-warning alert_code"><strong><small>私密代码长度不可以超过40字节</small></strong></div>
                    </div>

                     <div>
                        <p class="text-danger"><strong id="alert"></strong></p>

                        <co class="code">随机码 ==> <bg class="text-danger">{{ num_code }}</bg></co>
                        <div class="input code_box">
                            <input type="text" id="random_code" class="input_user" placeholder="随机码" name="random_code" required="required"/>
                        </div>
                     </div>
                        <button class="sgin_btn btn btn-danger btn-block">注 册</button>

                </form></div></div>
            </div>
            </div>

        <br>
            <div class="row">
                <div class="col-lg-3 col-lg-push-0">
                <div class="panel panel-danger">
                    <div class="panel-heading text-center"><h2><span class="glyphicon glyphicon-indent-right"></span> 压力测试</h2></div>
                    <div class="panel-body"><h4>在这个时代<br>压力总是使用相同的冗余代码<br>我们在应力达到瞬时攻击的可能。你不会失望的！</h4></div>
            </div></div>

            <div class="col-lg-3 col-lg-push-1">
                <div class="panel panel-info">
                    <div class="panel-heading text-center"><h2><span class="glyphicon glyphicon-user"></span> 客户</h2></div>
                    <div class="panel-body"><h4>我们珍视我们的客户。当你购买一个订阅我们的DDOS服务，你可以有购买的信心，总是会有支持，所以你可以保持IP启动！.</h4></div>

                </div>
            </div>

        <div class="col-lg-3 col-lg-push-2">
                <div class="panel panel-success">
                    <div class="panel-heading text-center"><h2><span class="glyphicon glyphicon-headphones"></span> 客服</h2></div>
                    <div class="panel-body"><h4>在任何时间<br>我们都会为您提供一个工作服务<br>让你能够放心的使用我们的程序。.</h4></div>
        </div>
        </div>
        </div>
        </div>
    </div>
    <script type="text/javascript" src="{{ url_for('static',filename='exts_js/sgin_up.js') }}"></script>
    <script type="text/javascript" src="{{ url_for('static',filename='js/canvas-nest.js') }}"></script>
</body>
</html>

templates/user.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="{{ url_for('static',filename='css/bootstrap.min.css') }}">
    <link rel="stylesheet" href="{{ url_for('static',filename='style/user.css') }}">
    <script type="text/javascript" src="{{ url_for('static',filename='js/jquery.min.js') }}"></script>
    <title>控制台</title>
</head>
<body>
<div>

<div class="navbar navbar-default">x
    <a href="./" class="navbar-brand"><span class="glyphicon glyphicon-cloud"></span></a>

    <div class="collapse navbar-collapse">
        <ul class="nav navbar-nav">
            <li class="action"><a href=""><strong>主页</strong></a></li>
        </ul>
    </div>
</div>

<div class="row">
    <div class="col-lg-3 spidebar">

    <ul class="">

    </ul>

    </div>
</div>

</div>
</body>
</html>